# API Gateway
Resources:
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: socless-public

  APIGatewayPrivate:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: soclessPrivate
      EndpointConfiguration:
        Types: 
          - PRIVATE
        VpcEndpointIds: 
          - vpce-0bd7392110e3dc083

Outputs:
  APIGatewayID:
    Value:
      Ref: APIGateway

  APIGatewayRootResourceId:
    Value:
      Fn::GetAtt:
        - APIGateway
        - RootResourceId

  APIGatewayIDPrivate:
    Value:
      Ref: APIGatewayPrivate

  APIGatewayRootResourceIdPrivate:
    Value:
      Fn::GetAtt:
        - APIGatewayPrivate
        - RootResourceId